yd_portfolio_homepage:
    path:     /
    defaults: { _controller: YDPortfolioBundle:Portfolio:index }

yd_portfolio_work:
    path:     /work/{slug}
    defaults: { _controller: YDPortfolioBundle:Portfolio:work}
