yd_portfolio_homepage:
    path:     /
    defaults: { _controller: YDPortfolioBundle:Portfolio:index }

yd_portfolio_work:
    path:     /work/{slug}
    defaults: { _controller: YDPortfolioBundle:Portfolio:work}

yd_portfolio_add:
    path: /admin/add
    defaults:
        _controller: YDPortfolioBundle:Portfolio:add

yd_portfolio_edit:
    path: /admin/edit/{id}
    defaults:
        _controller: YDPortfolioBundle:Portfolio:edit

yd_portfolio_delete:
    path: /admin/delete/{id}
    defaults:
      _controller: YDPortfolioBundle:Portfolio:delete
