yd_core_cv:
    path:     /cv
    defaults: { _controller: YDCoreBundle:Core:cv }

yd_core_about:
    path:     /about
    defaults: { _controller: YDCoreBundle:Core:about}

yd_core_contact:
    path:     /contact
    defaults: {_controller: YDCoreBundle:Core:contact}
